name: Deploy to Server

on:
  push:
    branches:
      - main
env:
  SERVER_IP: 62.72.7.32
  SERVER_USER: root

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Copiar archivos al servidor
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "."
          target: "/root/app"

      - name: Construir y ejecutar contenedores en el servidor
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/app
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
            docker compose down
            docker compose up -d --build
            sleep 10 # Esperar a que la base de datos esté lista
            docker exec next_app npx prisma migrate deploy
